return {
  { prefix = "'a",  body = "\\alpha",                desc = "Math: Alpha" },
  { prefix = "'0",  body = "\\emptyset",             desc = "Math: Empty Set" },
  { prefix = "'2",  body =  "\\sqrt",                desc = "Math: Square Root" },
  { prefix = "'6",  body =  "\\partial",             desc = "Math: Partial" },
  { prefix = "'8",  body = "\\infty",                desc = "Math: infty" },
  { prefix = "'=",  body = "\\equiv",                desc = "Math: equiv" },
  { prefix = "'\\", body = "\\setminus",             desc = "Math: setminus" },
  { prefix = "'.",  body = "\\cdot",                 desc = "Math: cdot" },
  { prefix = "'*",  body = "\\times",                desc = "Math: times" },
  { prefix = "'<",  body = "\\langle",               desc = "Math: langle" },
  { prefix = "'>",  body = "\\rangle",               desc = "Math: rangle" },
  { prefix = "'H",  body = "\\hbar",                 desc = "Math: hbar" },
  { prefix = "'+",  body = "\\dagger",               desc = "Math: dagger" },
  { prefix = "'[",  body = "\\subseteq",             desc = "Math: subseteq" },
  { prefix = "']",  body = "\\supseteq",             desc = "Math: supseteq" },
  { prefix = "'(",  body = "\\subset",               desc = "Math: subset" },
  { prefix = "')",  body = "\\supset",               desc = "Math: supset" },
  { prefix = "'A",  body = "\\forall",               desc = "Math: forall" },
  { prefix = "'B",  body = "\\boldsymbol",           desc = "Math: boldsymbol" },
  { prefix = "'E",  body = "\\exists",               desc = "Math: exists" },
  { prefix = "'N",  body = "\\nabla",                desc = "Math: nabla" },
  { prefix = "jj",  body = "\\downarrow",            desc = "Math: downarrow" },
  { prefix = "jJ",  body = "\\Downarrow",            desc = "Math: Downarrow" },
  { prefix = "jk",  body = "\\uparrow",              desc = "Math: uparrow" },
  { prefix = "jK",  body = "\\Uparrow",              desc = "Math: Uparrow" },
  { prefix = "jh",  body = "\\leftarrow",            desc = "Math: leftarrow" },
  { prefix = "jH",  body = "\\Leftarrow",            desc = "Math: Leftarrow" },
  { prefix = "jl",  body = "\\rightarrow",           desc = "Math: rightarrow" },
  { prefix = "jL",  body = "\\Rightarrow",           desc = "Math: Rightarrow" },
  { prefix = "'a",  body = "\\alpha",                desc = "Math: alpha" },
  { prefix = "'b",  body = "\\beta",                 desc = "Math: beta" },
  { prefix = "'c",  body = "\\chi",                  desc = "Math: chi" },
  { prefix = "'d",  body = "\\delta",                desc = "Math: delta" },
  { prefix = "'e",  body = "\\epsilon",              desc = "Math: epsilon" },
  { prefix = "'f",  body = "\\phi",                  desc = "Math: phi" },
  { prefix = "'g",  body = "\\gamma",                desc = "Math: gamma" },
  { prefix = "'h",  body = "\\eta",                  desc = "Math: eta" },
  { prefix = "'i",  body = "\\iota",                 desc = "Math: iota" },
  { prefix = "'k",  body = "\\kappa",                desc = "Math: kappa" },
  { prefix = "'l",  body = "\\lambda",               desc = "Math: lambda" },
  { prefix = "'m",  body = "\\mu",                   desc = "Math: mu" },
  { prefix = "'n",  body = "\\nu",                   desc = "Math: nu" },
  { prefix = "'p",  body = "\\pi",                   desc = "Math: pi" },
  { prefix = "'q",  body = "\\theta",                desc = "Math: theta" },
  { prefix = "'r",  body = "\\rho",                  desc = "Math: rho" },
  { prefix = "'s",  body = "\\sigma",                desc = "Math: sigma" },
  { prefix = "'t",  body = "\\tau",                  desc = "Math: tau" },
  { prefix = "'y",  body = "\\psi",                  desc = "Math: psi" },
  { prefix = "'u",  body = "\\upsilon",              desc = "Math: upsilon" },
  { prefix = "'w",  body = "\\omega",                desc = "Math: omega" },
  { prefix = "'z",  body = "\\zeta",                 desc = "Math: zeta" },
  { prefix = "'x",  body = "\\xi",                   desc = "Math: xi" },
  { prefix = "'D",  body = "\\Delta",                desc = "Math: Delta" },
  { prefix = "'F",  body = "\\Phi",                  desc = "Math: Phi" },
  { prefix = "'G",  body = "\\Gamma",                desc = "Math: Gamma" },
  { prefix = "'L",  body = "\\Lambda",               desc = "Math: Lambda" },
  { prefix = "'P",  body = "\\Pi",                   desc = "Math: Pi" },
  { prefix = "'Q",  body = "\\Theta",                desc = "Math: Theta" },
  { prefix = "'S",  body = "\\Sigma",                desc = "Math: Sigma" },
  { prefix = "'U",  body = "\\Upsilon",              desc = "Math: Upsilon" },
  { prefix = "'W",  body = "\\Omega",                desc = "Math: Omega" },
  { prefix = "'X",  body = "\\Xi",                   desc = "Math: Xi" },
  { prefix = "'Y",  body = "\\Psi",                  desc = "Math: Psi" },
  { prefix = "ve",  body = "\\varepsilon",           desc = "Math: varepsilon" },
  { prefix = "vf",  body = "\\varphi",               desc = "Math: varphi" },
  { prefix = "vk",  body = "\\varkappa",             desc = "Math: varkappa" },
  { prefix = "vp",  body = "\\varpi",                desc = "Math: varpi" },
  { prefix = "vq",  body = "\\vartheta",             desc = "Math: vartheta" },
  { prefix = "vr",  body = "\\varrho",               desc = "Math: varrho" },
  { prefix = "#-",  body = "\\overline{$1} $0",      desc = "Math: overline" },
  { prefix = "''",  body = "'$1' $0",                desc = "Math: default" },

  { prefix = "ii",  body = "$$1$ $0",                desc = "Create inline math formula" },
  { prefix = "dd",  body = "$$ $1 $$$0",             desc =  "Create display math formula" },
  { prefix = "id",  body = "$\\displaystyle $1$ $0", desc = "Create inline math formula with display style" },
  { prefix = "II",  body = "\\($1\\) $0",            desc =  "Create inline math formula" },
  { prefix = "DD",  body = "\\$1\\$0",               desc = "Create display math formula" },

  { prefix = "left", body = "\\left" },
  { prefix = "right", body = "\\right" },
  { prefix = "langle", body = "\\langle " },
  { prefix = "rangle", body = "\\rangle " },
  { prefix = "lfloor", body = "\\lfloor " },
  { prefix = "rfloor", body = "\\rfloor " },
  { prefix = "lceil", body = "\\lceil " },
  { prefix = "rceil", body = "\\rceil " },
  { prefix = "ulcorner", body = "\\ulcorner " },
  { prefix = "urcorner", body = "\\urcorner " },
  { prefix = "llcorner", body = "\\llcorner " },
  { prefix = "lrcorner", body = "\\lrcorner " },
  { prefix = "abs", body = "\\left| $1 \\right| $0" },
  { prefix = "norm", body = "\\left\\| $1 \\right\\| $0" },
  { prefix = "(", body = "\\left( $1 \\right) $0" },
  { prefix = "[", body = "\\left[ $1 \\right] $0" },
  { prefix = "{", body = "\\left\\{ $1 \\right\\\\} $0" },
  { prefix = "<", body = "\\left\\langle $1 \\right\\rangle $0" },
  { prefix = "floor", body = "\\left\\lfloor $1 \\right\\rfloor $0" },
  { prefix = "ceil", body = "\\left\\lceil $1 \\right\\rceil $0" },
  { prefix = "oo", body = "\\infty " },
  { prefix = "degr", body = "^{\\circ} " },
  { prefix = "mbf", body = "\\mathbf{$1}$0" },
  { prefix = "mbb", body = "\\mathbb{$1}$0" },
  { prefix = "mc",  body = "\\mathcal{$1} $0",       desc = "Math: mathcal" },
  { prefix = "equivalent", body = "\\Leftrightarrow " },
  { prefix = "implies", body = "\\Rightarrow " },
  { prefix = "deriv", body = "\\frac{d${1:f}}{d${2:x}} $0" },
  { prefix = "pderiv", body = "\\frac{\\partial ${1:f}}{\\partial ${2:x}} $0" },
  { prefix = "cases", body = "\\begin{cases}","\t$1 &\\text{$2}\\\\\\\\","\t$3 &\\text{$4}\\\\\\\\$5","\\end{cases} $0" },
  { prefix = "align", body = "\\begin{${1|align,align*,aligned|}}","\t$2\\\\\\\\","\t$3\\\\\\\\$4","\\end{$1} $0" },
  { prefix = "frac", body = "\\frac{$1}{$2}$0" },
  { prefix = "sqrt", body = "\\sqrt[$1]{$2}$0" },
  { prefix = "alpha", body = "\\alpha " },
  { prefix = "beta", body = "\\beta " },
  { prefix = "gamma", body = "\\gamma " },
  { prefix = "Gamma", body = "\\Gamma " },
  { prefix = "vargamma", body = "\\vargamma " },
  { prefix = "delta", body = "\\delta " },
  { prefix = "Delta", body = "\\Delta " },
  { prefix = "epsilon", body = "\\epsilon " },
  { prefix = "varepsilon", body = "\\varepsilon " },
  { prefix = "zeta", body = "\\zeta " },
  { prefix = "eta", body = "\\eta " },
  { prefix = "theta", body = "\\theta " },
  { prefix = "Theta", body = "\\Theta " },
  { prefix = "vartheta", body = "\\vartheta " },
  { prefix = "iota", body = "\\iota " },
  { prefix = "kappa", body = "\\kappa " },
  { prefix = "lambda", body = "\\lambda " },
  { prefix = "Lambda", body = "\\Lambda " },
  { prefix = "mu", body = "\\mu " },
  { prefix = "nu", body = "\\nu " },
  { prefix = "xi", body = "\\xi " },
  { prefix = "Xi", body = "\\Xi " },
  { prefix = "pi", body = "\\pi " },
  { prefix = "Pi", body = "\\Pi " },
  { prefix = "varpi", body = "\\varpi " },
  { prefix = "rho", body = "\\rho " },
  { prefix = "varrho", body = "\\varrho " },
  { prefix = "sigma", body = "\\sigma " },
  { prefix = "Sigma", body = "\\Sigma " },
  { prefix = "varsigma", body = "\\varsigma " },
  { prefix = "tau", body = "\\tau " },
  { prefix = "upsilon", body = "\\upsilon " },
  { prefix = "Upsilon", body = "\\Upsilon " },
  { prefix = "phi", body = "\\phi " },
  { prefix = "Phi", body = "\\Phi " },
  { prefix = "varphi", body = "\\varphi " },
  { prefix = "chi", body = "\\chi " },
  { prefix = "psi", body = "\\psi " },
  { prefix = "Psi", body = "\\Psi " },
  { prefix = "omega", body = "\\omega " },
  { prefix = "Omega", body = "\\Omega " },
  { prefix = "digamma", body = "\\digamma " },
  { prefix = "Digamma", body = "\\Digamma " },
  { prefix = "aleph", body = "\\aleph " },
  { prefix = "beth", body = "\\beth " },
  { prefix = "gimel", body = "\\gimel " },
  { prefix = "daleth", body = "\\daleth " },
  { prefix = "cup", body = "\\cup " },
  { prefix = "cap", body = "\\cap " },
  { prefix = "sqcup", body = "\\sqcup " },
  { prefix = "sqcap", body = "\\sqcap " },
  { prefix = "subset", body = "\\subset " },
  { prefix = "notsubset", body = "\\not\\subset " },
  { prefix = "subseteq", body = "\\subseteq " },
  { prefix = "nsubseteq", body = "\\nsubseteq " },
  { prefix = "sqsubset", body = "\\sqsubset " },
  { prefix = "sqsubseteq", body = "\\sqsubseteq " },
  { prefix = "sqsupset", body = "\\sqsupset " },
  { prefix = "sqsupseteq", body = "\\sqsupseteq " },
  { prefix = "supset", body = "\\supset " },
  { prefix = "notsupset", body = "\\not\\supset " },
  { prefix = "supseteq", body = "\\supseteq " },
  { prefix = "nsupseteq", body = "\\nsupseteq " },
  { prefix = "in", body = "\\in " },
  { prefix = "ni", body = "\\ni " },
  { prefix = "notin", body = "\\not\\in " },
  { prefix = "not", body = "\\not " },
  { prefix = "varnothing", body = "\\varnothing " },
  { prefix = "emptyset", body = "\\emptyset " },
  { prefix = "setminus", body = "\\setminus " },
  { prefix = "equiv", body = "\\equiv " },
  { prefix = "forall", body = "\\forall " },
  { prefix = "exists", body = "\\exists " },
  { prefix = "nexists", body = "\\nexists " },
  { prefix = "therefore", body = "\\therefore " },
  { prefix = "because", body = "\\because " },
  { prefix = "neg", body = "\\neg " },
  { prefix = "lnot", body = "\\lnot " },
  { prefix = "vee", body = "\\vee " },
  { prefix = "lor", body = "\\lor " },
  { prefix = "wedge", body = "\\wedge " },
  { prefix = "land", body = "\\land " },
  { prefix = "vdash", body = "\\vdash " },
  { prefix = "dashv", body = "\\dashv " },
  { prefix = "models", body = "\\models " },
  { prefix = "acute", body = "\\acute{$1}$0" },
  { prefix = "breve", body = "\\breve{$1}$0" },
  { prefix = "check", body = "\\check{$1}$0" },
  { prefix = "mathring", body = "\\mathring{$1}$0" },
  { prefix = "grave", body = "\\grave{$1}$0" },
  { prefix = "dot", body = "\\dot{$1}$0" },
  { prefix = "ddot", body = "\\ddot{$1}$0" },
  { prefix = "hat", body = "\\hat{$1}$0" },
  { prefix = "tilde", body = "\\tilde{$1}$0" },
  { prefix = "bar", body = "\\bar{$1}$0" },
  { prefix = "vec", body = "\\vec{$1}$0" },
  { prefix = "mathbf", body = "\\mathbf{$1}$0" },
  { prefix = "mathbb", body = "\\mathbb{$1}$0" },
  { prefix = "mathcal", body = "\\mathcal{$1}$0" },
  { prefix = "mathfrak", body = "\\mathfrak{$1}$0" },
  { prefix = "mathscr", body = "\\mathscr{$1}$0" },
  { prefix = "overline", body = "\\overline{$1}$0" },
  { prefix = "widehat", body = "\\widehat{$1}$0" },
  { prefix = "widetilde", body = "\\widetilde{$1}$0" },
  { prefix = "overbrace", body = "\\overbrace{$1}^{$2}$0" },
  { prefix = "underbrace", body = "\\underbrace{$1}_{$2}$0" },
  { prefix = "sin", body = "\\sin " },
  { prefix = "cos", body = "\\cos " },
  { prefix = "tan", body = "\\tan " },
  { prefix = "sec", body = "\\sec " },
  { prefix = "csc", body = "\\csc " },
  { prefix = "cot", body = "\\cot " },
  { prefix = "exp", body = "\\exp " },
  { prefix = "log", body = "\\log_{$1} $0" },
  { prefix = "ln", body = "\\ln " },
  { prefix = "lg", body = "\\lg " },
  { prefix = "sinh", body = "\\sinh " },
  { prefix = "cosh", body = "\\cosh " },
  { prefix = "tanh", body = "\\tanh " },
  { prefix = "coth", body = "\\coth " },
  { prefix = "det", body = "\\det " },
  { prefix = "dim", body = "\\dim " },
  { prefix = "ker", body = "\\ker " },
  { prefix = "deg", body = "\\deg " },
  { prefix = "arg", body = "\\arg " },
  { prefix = "gcd", body = "\\gcd " },
  { prefix = "arcsin", body = "\\arcsin " },
  { prefix = "arccos", body = "\\arccos " },
  { prefix = "arctan", body = "\\arctan " },
  { prefix = "arccsc", body = "\\operatorname{arccsc} " },
  { prefix = "arcsec", body = "\\operatorname{arcsec} " },
  { prefix = "arccot", body = "\\operatorname{arccot} " },
  { prefix = "arsinh", body = "\\operatorname{arsinh} " },
  { prefix = "arcosh", body = "\\operatorname{arcosh} " },
  { prefix = "artanh", body = "\\operatorname{artanh} " },
  { prefix = "csch", body = "\\operatorname{csch} " },
  { prefix = "sech", body = "\\operatorname{sech} " },
  { prefix = "arcsch", body = "\\operatorname{arcsch} " },
  { prefix = "arsech", body = "\\operatorname{arsech} " },
  { prefix = "arcoth", body = "\\operatorname{arcoth} " },
  { prefix = "min", body = "\\min " },
  { prefix = "max", body = "\\max " },
  { prefix = "inf", body = "\\inf " },
  { prefix = "sup", body = "\\sup " },
  { prefix = "liminf", body = "\\liminf " },
  { prefix = "limsup", body = "\\limsup " },
  { prefix = "limits", body = "\\limits_{$1}^{$2} $0" },
  { prefix = "lim", body = "\\lim \\limits_{${1:x} \\to ${2:\\infty}} $0" },
  { prefix = "leq", body = "\\leq " },
  { prefix = "geq", body = "\\geq " },
  { prefix = "neq", body = "\\neq " },
  { prefix = "leqslant", body = "\\leqslant " },
  { prefix = "geqslant", body = "\\geqslant " },
  { prefix = "ll", body = "\\ll " },
  { prefix = "lll", body = "\\lll " },
  { prefix = "gg", body = "\\gg " },
  { prefix = "ggg", body = "\\ggg " },
  { prefix = "nless", body = "\\nless " },
  { prefix = "nleq", body = "\\nleq " },
  { prefix = "nleqslant", body = "\\nleqslant " },
  { prefix = "ngtr", body = "\\ngtr " },
  { prefix = "ngeq", body = "\\ngeq " },
  { prefix = "ngeqslant", body = "\\ngeqslant " },
  { prefix = "approx", body = "\\approx " },
  { prefix = "asymp", body = "\\asymp " },
  { prefix = "prec", body = "\\prec " },
  { prefix = "nprec", body = "\\nprec " },
  { prefix = "preceq", body = "\\preceq " },
  { prefix = "npreceq", body = "\\npreceq " },
  { prefix = "succ", body = "\\succ " },
  { prefix = "nsucc", body = "\\nsucc " },
  { prefix = "succeq", body = "\\succeq " },
  { prefix = "nsucceq", body = "\\nsucceq " },
  { prefix = "propto", body = "\\propto " },
  { prefix = "doteq", body = "\\doteq " },
  { prefix = "triangle", body = "\\triangle " },
  { prefix = "triangleright", body = "\\triangleright " },
  { prefix = "triangleleft", body = "\\triangleleft " },
  { prefix = "angle", body = "\\angle " },
  { prefix = "measuredangle", body = "\\measuredangle " },
  { prefix = "ell", body = "\\ell " },
  { prefix = "parallel", body = "\\parallel " },
  { prefix = "nparallel", body = "\\nparallel " },
  { prefix = "bowtie", body = "\\bowtie " },
  { prefix = "perp", body = "\\perp " },
  { prefix = "notperp", body = "\\not\\perp " },
  { prefix = "smile", body = "\\smile " },
  { prefix = "frown", body = "\\frown " },
  { prefix = "circ", body = "\\circ " },
  { prefix = "degree", body = "\\degree " },
  { prefix = "cong", body = "\\cong " },
  { prefix = "ncong", body = "\\ncong " },
  { prefix = "sim", body = "\\sim " },
  { prefix = "simeq", body = "\\simeq " },
  { prefix = "nsim", body = "\\nsim " },
  { prefix = "bullet", body = "\\bullet " },
  { prefix = "diamond", body = "\\diamond " },
  { prefix = "uplus", body = "\\uplus " },
  { prefix = "oplus", body = "\\oplus " },
  { prefix = "ominus", body = "\\ominus " },
  { prefix = "odot", body = "\\odot " },
  { prefix = "otimes", body = "\\otimes " },
  { prefix = "oslash", body = "\\oslash " },
  { prefix = "upharpoonright", body = "\\upharpoonright " },
  { prefix = "cdot", body = "\\cdot " },
  { prefix = "cdots", body = "\\cdots " },
  { prefix = "ldots", body = "\\ldots " },
  { prefix = "vdots", body = "\\vdots " },
  { prefix = "ddots", body = "\\ddots " },
  { prefix = "pm", body = "\\pm " },
  { prefix = "mp", body = "\\mp " },
  { prefix = "times", body = "\\times " },
  { prefix = "div", body = "\\div " },
  { prefix = "ast", body = "\\ast " },
  { prefix = "mid", body = "\\mid " },
  { prefix = "nmid", body = "\\nmid " },
  { prefix = "partial", body = "\\partial " },
  { prefix = "nabla", body = "\\nabla " },
  { prefix = "hbar", body = "\\hbar " },
  { prefix = "star", body = "\\star " },
  { prefix = "surd", body = "\\surd " },
  { prefix = "checkmark", body = "\\checkmark " },
  { prefix = "bigcirc", body = "\\bigcirc " },
  { prefix = "amalg", body = "\\amalg " },
  { prefix = "bigtriangleup", body = "\\bigtriangleup " },
  { prefix = "bigtriangledown", body = "\\bigtriangledown " },
  { prefix = "dagger", body = "\\dagger " },
  { prefix = "ddagger", body = "\\ddagger " },
  { prefix = "wr", body = "\\wr " },
  { prefix = "wp", body = "\\wp " },
  { prefix = "Re", body = "\\Re " },
  { prefix = "Im", body = "\\Im " },
  { prefix = "imath", body = "\\imath " },
  { prefix = "jmath", body = "\\jmath " },
  { prefix = "eth", body = "\\eth " },
  { prefix = "prime", body = "\\prime " },
  { prefix = "Box", body = "\\Box " },
  { prefix = "bot", body = "\\bot " },
  { prefix = "top", body = "\\top " },
  { prefix = "infty", body = "\\infty " },
  { prefix = "sum", body = "\\sum \\limits_{$1}^{$2}$0" },
  { prefix = "prod", body = "\\prod_{$1}^{$2}$0" },
  { prefix = "dif", body = "\\mathop{}\\!\\mathrm{d}" },
  { prefix = "int", body = "\\int_{$1}^{$2}$0" },
  { prefix = "iint", body = "\\iint_{$1}^{$2}$0" },
  { prefix = "iiint", body = "\\iiint_{$1}^{$2}$0" },
  { prefix = "oint", body = "\\oint_{$1}^{$2}$0" },
  { prefix = "bigcup", body = "\\bigcup_{$1}^{$2}$0" },
  { prefix = "bigcap", body = "\\bigcap_{$1}^{$2}$0" },
  { prefix = "bigvee", body = "\\bigvee_{$1}^{$2}$0" },
  { prefix = "bigwedge", body = "\\bigwedge_{$1}^{$2}$0" },
  { prefix = "coprod", body = "\\coprod_{$1}^{$2}$0" },
  { prefix = "biguplus", body = "\\biguplus_{$1}^{$2}$0" },
  { prefix = "bigodot", body = "\\bigodot_{$1}^{$2}$0" },
  { prefix = "bigoplus", body = "\\bigoplus_{$1}^{$2}$0" },
  { prefix = "bigotimes", body = "\\bigotimes_{$1}^{$2}$0" },
  { prefix = "iff", body = "\\iff " },
  { prefix = "implies", body = "\\implies " },
  { prefix = "rightarrow", body = "\\rightarrow " },
  { prefix = "to", body = "\\to " },
  { prefix = "nrightarrow", body = "\\nrightarrow " },
  { prefix = "longrightarrow", body = "\\longrightarrow " },
  { prefix = "Rightarrow", body = "\\Rightarrow " },
  { prefix = "Longrightarrow", body = "\\Longrightarrow " },
  { prefix = "Leftarrow", body = "\\Leftarrow " },
  { prefix = "Longleftarrow", body = "\\Longleftarrow " },
  { prefix = "Leftrightarrow", body = "\\Leftrightarrow " },
  { prefix = "Longleftrightarrow", body = "\\Longleftrightarrow " },
  { prefix = "nRightarrow", body = "\\nRightarrow " },
  { prefix = "leadsto", body = "\\leadsto " },
  { prefix = "mapsto", body = "\\mapsto " },
  { prefix = "longmapsto", body = "\\longmapsto " },
  { prefix = "longleftarrow", body = "\\longleftarrow " },
  { prefix = "leftarrow", body = "\\leftarrow " },
  { prefix = "gets", body = "\\gets " },
  { prefix = "leftrightarrow", body = "\\leftrightarrow " },
  { prefix = "longleftrightarrow", body = "\\longleftrightarrow " },
  { prefix = "downarrow", body = "\\downarrow " },
  { prefix = "Downarrow", body = "\\Downarrow " },
  { prefix = "uparrow", body = "\\uparrow " },
  { prefix = "Uparrow", body = "\\Uparrow " },
  { prefix = "updownarrow", body = "\\updownarrow " },
  { prefix = "Updownarrow", body = "\\Updownarrow " },
  { prefix = "hookleftarrow", body = "\\hookleftarrow " },
  { prefix = "hookrightarrow", body = "\\hookrightarrow " },
  { prefix = "leftharpoonup", body = "\\leftharpoonup " },
  { prefix = "rightharpoonup", body = "\\rightharpoonup " },
  { prefix = "leftharpoondown", body = "\\leftharpoondown " },
  { prefix = "rightharpoondown", body = "\\rightharpoondown " },
  { prefix = "rightleftharpoons", body = "\\rightleftharpoons " },
  { prefix = "nearrow", body = "\\nearrow " },
  { prefix = "searrow", body = "\\searrow " },
  { prefix = "nwarrow", body = "\\nwarrow " },
  { prefix = "swarrow", body = "\\swarrow " },
  { prefix = "overrightarrow", body = "\\overrightarrow{$1}$0" },
  { prefix = "underrightarrow", body = "\\underrightarrow{$1}$0" },
  { prefix = "overleftarrow", body = "\\overleftarrow{$1}$0" },
  { prefix = "underleftarrow", body = "\\underleftarrow{$1}$0" },
  { prefix = "overleftrightarrow", body = "\\overleftrightarrow{$1}$0" },
  { prefix = "underleftrightarrow", body = "\\underleftrightarrow{$1}$0" },
}
