# Autostart

exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar & dunst & waypaper --restore
exec-once = nm-applet --indicator & gammastep-indicator
# exec-once = [workspace special:default silent] $terminal
# exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP QT_QPA_PLATFORMTHEME
# exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
# exec-once = xprop -root -f _XWAYLAND_GLOBAL_OUTPUT_SCALE 32c -set _XWAYLAND_GLOBAL_OUTPUT_SCALE 2
# exec-once = swaylock --screenshots --clock --timestr '%-I:%M %p' --datestr '%-d %b %Y' --indicator --indicator-radius 100 --indicator-thickness 7 --effect-blur 7x5 --effect-vignette 0.5:0.5 --ring-color 333333 --key-hl-color 880033 --line-color 00000000 --inside-color 00000088 --separator-color 00000000 --font 'Iosevka Comfy Duo'
# exec-once = hyprlock || hyprctl dispatch exit

