# Window Rules

# windowrule = float, ^(qt5ct|qt6ct)$
windowrule {
  name = float
  match:title = ^(nwg-displays|Open File|satty|Picture-in-Picture|Qalculate!)$
  float = on
}
windowrule {
  name = pin
  match:title = ^(Picture-in-Picture)$
  pin = on
}
windowrule {
  name = MPV
  match:class = ^(mpv)$
  idle_inhibit = focus
}
windowrule {
  name = Firefox
  match:class = ^(firefox)$
  idle_inhibit = fullscreen
}
# windowrule = float, class:^(org.kde.polkit-kde-authentication-agent-1)$


