#!/usr/bin/env sh

file="$HOME/.local/bookmarks.txt"

add() {
  bookmark="${1:-$(wl-paste --primary)}"

  if [ -z "$bookmark" ]; then
    notify-send "No text selected"
    return
  fi

  if grep -q "^$bookmark$" "$file"; then
    notify-send "Already bookmarked!: $bookmark"
  else
    echo "$bookmark" >> "$file"
    notify-send "Bookmarked: $bookmark"
  fi
}

list() {
  wtype "$(grep -v 'A#' "$file" | tofi --prompt-text 'bookmark: ')"
}

commands() {
  # Read selection before tofi steals focus
  selection="$(wl-paste --primary)"
  command="$(printf "add\nlist\nview" | tofi --prompt-text 'command: ')"
  case "$command" in
    add)  add "$selection" ;;
    list) list ;;
    view) kitty --single-instance vi "$file" ;;
    *)    notify-send "Usage: $0 {add|list}" ;;
  esac
}

case "$1" in
  add)  add ;;
  list) list ;;
  view) kitty --single-instance vi "$file" ;;
  commands) commands ;;
  *)    echo "Usage: $0 {add|list}" ;;
esac
