set -g base-index 1
set -g mouse on
set -g mode-keys vi
set -g status-position top
set -g renumber-windows on
set -sg escape-time 0
set -g history-limit 5000
set -g prefix M-f
unbind C-b
bind M-f send-prefix
set -g default-shell fish
set -g default-terminal screen-256color
set -g extended-keys-format csi-u
bind '`' switch-client -t '{marked}'
bind-key M-h split-window -hc '#{pane_current_path}'
bind-key M-v split-window -vc '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'
bind Space last-window
bind-key M-Space switch-client -l
bind-key M-j choose-window 'join-pane -h -s "%%"'
bind-key M-J choose-window 'join-window -s "%%"'
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind P paste-buffer
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
